### ISSUE TITLE
which count matrices should be used from the output generated by the "nac" workflow of the latest kb_python?

### ISSUE THREAD

**Issue by mt1022** [pachterlab/CGCCP_2023#2]
As the `lamanno` workflow has been deprecated in the latest version of kb_python, How should users run the biVI pipeline with the output produced by the `nac` workflow?

I made the following changes to the example code based on my understanding. I am not sure whether these steps are correct. Any suggestions?

1. The `adata.X` defaults to mature counts when loading loom. However, spliced counts = mature+ambiguous counts based on kb-python tutorial on biorxiv. Therefore, I modified adata as follows: 

  ```python
  adata.X = adata.layers['ambiguous'] + adata.layers['mature']
  ```

2. When creating the concatenated spliced + unspliced adata, the original code was modified as follows:

  ```python
  adata_spliced   = anndata.AnnData(adata.layers['ambiguous'] + adata.layers['mature'])
  adata_unspliced = anndata.AnnData(adata.layers['nascent'])
  ```

**Comment by mtcarilli** [comment]
Yes, that is correct! If you are working with single nucleus rather than single cell data, we may suggest using 'ambiguous'+'nascent' layers as unspliced and only 'mature' as spliced, but for single cell where reads are more likely to be mature than nascent, adding ambiguous and mature layers and using them as the spliced layer is good!

**Comment by mt1022** [comment]
That's good to know. Thanks!
